# CI de Nível 03 - Disparo após a conclusão de outra pipeline

name: "Execução por Deploy"

on:
  workflow_run:
    workflows: ["Execução Manual", "Scheduled Executation"]
    types:
      - completed

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando Dependencias
        run: yarn

      - name: Executando testes e2e
        run: yarn run test
